### ISSUE TITLE
ModuleNotFoundError: No module named 'soundfile'

### ISSUE THREAD

**Issue by Aaack-Aardvark** [yukiarimo/yuna-ai#110]
In the main branch, after a fresh hit pull I get this error trying to start yuna-ai.sh:

```
Traceback (most recent call last):

  File "/home/spike/Documents/Yuna/yuna-ai/index.py", line 5, in <module>
    from lib.router import generate_audiobook, handle_history_request, handle_image_request, handle_message_request, handle_audio_request, services, handle_search_request, handle_textfile_request

  File "/home/spike/Documents/Yuna/yuna-ai/lib/router.py", line 5, in <module>
    from lib.vision import capture_image

  File "/home/spike/Documents/Yuna/yuna-ai/lib/vision.py", line 2, in <module>
    from lib.audio import speak_text

  File "/home/spike/Documents/Yuna/yuna-ai/lib/audio.py", line 6, in <module>
    import soundfile as sf

ModuleNotFoundError: No module named 'soundfile'
```

To reproduce I just either navigate to the directory and ·/yuna.sh or sh ./yuna.sh, the error is instantaneous and the start aborts.

> OS: Pop!_OS 22.04 LTS (Linux)
> Browser: Brave Browser Version 1.71.118 Chromium: 130.0.6723.70 (Official Build) (64-bit)
> Yuna.ai version: 7.0

**Comment by yukiarimo** [comment]
1. Gonna add this to requirements today.
2. `pip install {module_name}`
